@startuml

package domain {
    class TransactionService

    class Transaction
}

package persistence {
    class DBTransactionRepository
}

TransactionService -> DBTransactionRepository
TransactionService -> Transaction

DBTransactionRepository -up-> Transaction

@enduml
