@startuml

skinparam defaultFontSize 25

package washing {

    interface Washer {
        void washClothes()
        void washDishes()
    }

    note top of Washer
        Interface
    endnote

    note left of Washer::washClothes
        Method of Interface
    endnote

    class HandWasher {
        void washClothes()
        void washDishes()
    }

    Washer <|... HandWasher
    note on link: Implements Interface

    note top of HandWasher
        Class
    endnote

    class Bucket

    HandWasher --> Bucket
    note on link: HandWasher uses Bucket
}

note top of washing
    Package
endnote

@enduml