name: Pattern examples
on:
  - push
  - pull_request
jobs:
  pattern-examples:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: compile
        working-directory: topics/sw_concepts/code/pattern-examples
        run: mvn install -DskipTests=true

      - name: lint
        working-directory: topics/sw_concepts/code/pattern-examples
        run: mvn pmd:check

      - name: check format
        working-directory: topics/sw_concepts/code/pattern-examples
        run: mvn spotless:check

      - name: run tests
        working-directory: topics/sw_concepts/code/pattern-examples
        run: mvn test
